language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo

stages:
  - lint
  - test
  - build_www

jobs:
  allow_failures:
    - rust: nightly
  include:
    - stage: build_www
      before_script: which wasm-pack || cargo install wasm-pack; which wasm-bindgen-cli || cargo install wasm-bindgen-cli
      script: ./examples/www/build.sh
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: target/pkg
        keep-history: true
        on:
          branch: master
    - stage: lint
      before_script: rustup component add clippy
      script: cargo clippy -- -D warnings
