[package]
name = "jval"
version = "0.1.0"
authors = ["George Kaplan <george@georgekaplan.xyz>"]
edition = "2018"

[dependencies]

[workspace]
members = [ "examples/cli", "examples/gtk", "examples/www" ]
