[package]
name = "gtk"
version = "0.1.0"
authors = ["George Kaplan <george.kaplan@visionistinc.com>"]
edition = "2018"

[dependencies]
jval = { path = "../.." }
gtk = { version = "0.6.0", features = [ "v3_16" ] }
relm = "0.16.0"
relm-derive = "0.16.0"
